name: CI
on:
  push:
    branches:
      - main
      - dev
      - dev-26-add-coveralls
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    name: "Unit tests using mocha for node 18.x.x"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - name: "Build"
      run: npm run build
    - name: "Tests"
      run: npm test
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run lint
  coverage:
    name: "Coverage"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build
    - name: "Coverage"
      run: npm run coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
